# Generated by Django 2.0 on 2018-06-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpyApp', '0002_auto_20180614_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpytable',
            name='adhaar_number',
            field=models.IntegerField(blank=True, db_column='Adhaar Number', null=True),
        ),
        migrations.AddField(
            model_name='dpytable',
            name='email',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='dpytable',
            name='mobile_number',
            field=models.IntegerField(blank=True, db_column='Mobile Number', null=True),
        ),
    ]
