# Generated by Django 2.0 on 2018-06-14 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpyApp', '0003_auto_20180614_0510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dpytable',
            options={'managed': False},
        ),
    ]
